services:
  - type: web 
    plan: free
    name: go-jiosaavn-api
    runtime: go
    repo: https://github.com/akadotsh/go-jiosaavn-api.git
    buildCommand: "go build -tags netgo -ldflags '-s -w' -o app ./cmd"
    startCommand: "go run ./cmd/main.go"